server:
  port: 8090

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DemoUCB
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/DemoUCB/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs
            user-name-attribute: preferred_username

        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: lpGFQz5yHVBT2YvobWhwHSDeGP38hFl2
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ===== M-CURSOS =====
        - id: m-cursos
          uri: lb://M-CURSOS
          predicates:
            - Path=/cursos/**

        - id: m-cursos-swagger
          uri: lb://M-CURSOS
          predicates:
            - Path=/m-cursos/openapi/**
          filters:
            - StripPrefix=1

        # ===== MS-RES (RESEÑAS) =====
        - id: ms-res
          uri: lb://ms-res
          predicates:
            - Path=/reviews/**

        - id: ms-res-swagger
          uri: lb://MS-RES
          predicates:
            - Path=/ms-res/v3/api-docs/**, /ms-res/swagger-ui/**
          filters:
            - StripPrefix=1

        # ===== EUREKA =====
        - id: eureka-web
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**

        # ===== MODULOS =====
        - id: m-modulos
          uri: lb://M-CURSOS
          predicates:
            - Path=/modulos/**
