server:
  port: 8090

spring:
  application:
    name: gateway
  
  security:
    oauth2:
      resourceserver:
          jwt:
            # 1. URL para validar la firma (coincide con el token de Angular)
            issuer-uri: http://localhost:8080/realms/DemoUCB
          # 2. URL interna para que Docker busque las llaves
            jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            # URL para que tu NAVEGADOR te redirija al login
            authorization-uri: http://localhost:8080/realms/DemoUCB/protocol/openid-connect/auth
            # URLs para que DOCKER se comunique internamente
            token-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            # Tu secreto actual
            client-secret: mmvbH3SUYERNi8GWd04QwieL4GHIPZLB
            # ESTA LÍNEA ES LA MAGIA PARA QUE NO DE "INVALID CREDENTIALS":
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para M-CURSOS
        - id: m-cursos
          uri: lb://M-CURSOS
          predicates:
            - Path=/cursos/**
        
        # Ruta para M-CURSOS Swagger
        - id: m-cursos-swagger
          uri: lb://M-CURSOS
          predicates:
            - Path=/m-cursos/openapi/**
          filters:
            - StripPrefix=1
            
        # Ruta para MS-RES
        - id: ms-res
          uri: lb://MS-RES
          predicates:
            - Path=/reviews/**
          filters:
            - StripPrefix=1

        # Ruta para MS-RES Swagger
        - id: ms-res-swagger
          uri: lb://MS-RES
          predicates:
            - Path=/ms-res/v3/api-docs/**, /ms-res/swagger-ui/**
          filters:
            - StripPrefix=1

        # Rutas para Eureka Dashboard
        - id: eureka-web
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
