server:
  port: 8090

spring:
  application:
    name: gateway
  

  security:
    oauth2:
      client:
        provider:
          keycloak:
            # Configuración manual para evitar errores de inicio
            authorization-uri: http://localhost:8080/realms/DemoUCB/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: 4QdeyiCKeskAP6TvTJ2pmDzh6qcu2Epn
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para MS-RES
        - id: ms-res
          uri: lb://MS-RES
          predicates:
            - Path=/reviews/**
          filters:
            - StripPrefix=1

        # Ruta para MS-RES Swagger
        - id: ms-res-swagger
          uri: lb://MS-RES
          predicates:
            - Path=/ms-res/v3/api-docs/**, /ms-res/swagger-ui/**
          filters:
            - StripPrefix=1

        # Ruta para M-CURSOS
        - id: m-cursos
          uri: lb://M-CURSOS
          predicates:
            - Path=/cursos/**
          # filters: StripPrefix=1 (Descomenta si tu controller no tiene /cursos)

        # Ruta para M-CURSOS Swagger
        - id: m-cursos-swagger
          uri: lb://M-CURSOS
          predicates:
            - Path=/m-cursos/openapi/**
          filters:
            - StripPrefix=1

        # Rutas para ver el panel de Eureka a través del Gateway
        - id: eureka-web
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
