server:
  port: 8090

spring:
  application:
    name: gateway
  
  # === SEGURIDAD OAUTH2 CLIENT (Login) ===
  security:
    oauth2:
      client:
        provider:
          keycloak:
            # BORRAMOS issuer-uri para evitar el error de inicio
            # issuer-uri: http://keycloak:8080/realms/DemoUCB
            
            # --- AGREGAMOS ESTAS 5 LÍNEAS NUEVAS ---
            # 1. URL para el navegador (Tu Mac -> Keycloak)
            authorization-uri: http://localhost:8080/realms/DemoUCB/protocol/openid-connect/auth
            
            # 2. URLs internas (Gateway -> Keycloak dentro de Docker)
            token-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs
            
            # 3. Campo para leer el nombre del usuario
            user-name-attribute: preferred_usernamegrant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid

  # === RUTAS Y FILTROS ===
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para MS-RES
        - id: ms-res
          uri: lb://MS-RES
          predicates:
            - Path=/reviews/**
          filters:
            - StripPrefix=1

        # Ruta para MS-RES Swagger
        - id: ms-res-swagger
          uri: lb://MS-RES
          predicates:
            - Path=/ms-res/v3/api-docs/**, /ms-res/swagger-ui/**
          filters:
            - StripPrefix=1

        # Ruta para M-CURSOS
        - id: m-cursos
          uri: lb://M-CURSOS
          predicates:
            - Path=/cursos/**
          # filters: StripPrefix=1 (Descomenta si tu controller no tiene /cursos)

        # Ruta para M-CURSOS Swagger
        - id: m-cursos-swagger
          uri: lb://M-CURSOS
          predicates:
            - Path=/m-cursos/openapi/**
          filters:
            - StripPrefix=1

        # Rutas para ver el panel de Eureka a través del Gateway
        - id: eureka-web
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/**
