server:
  port: 8081

spring:
  application:
    name: m-cursos
  
  # Conexión a la Base de Datos (Nombre del contenedor)
  datasource:
    url: jdbc:postgresql://postgres_cursos:5432/Curso-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Seguridad (Resource Server)
  security:
    oauth2:
      resourceserver:
        jwt:
          # 1. VALIDACIÓN: El token dirá que viene de "localhost" (porque te logueaste en el navegador)
          issuer-uri: http://localhost:8080/realms/DemoUCB
          
          # 2. CONEXIÓN: Pero Docker debe buscar las llaves en "keycloak" internamente
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

# Configuración Swagger
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs

# Conexión a Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
