server:
  port: 8082

spring:
  main:
    web-application-type: reactive   # si tu app es WebFlux

  application:
    name: ms-res

  datasource:
    url: jdbc:postgresql://postgres_cursos:5432/Curso-db
    username: postgres
    password: gatito71
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          # Lo que ve el navegador
          issuer-uri: http://localhost:8080/realms/DemoUCB
          # Lo que ve Docker internamente
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
