server:
  port: 8082

spring:
  application:
    name: ms-res
  
  datasource:
    url: jdbc:postgresql://postgres_cursos:5432/Curso-db
    username: postgres
    password: gatito71
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DemoUCB
          jwk-set-uri: http://keycloak:8080/realms/DemoUCB/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs

eureka:
  client:
    serviceUrl:              # 👈 igual que en m-cursos (U mayúscula)
      defaultZone: http://eureka-server:8761/eureka/
